### ISSUE TITLE
Incomplete database on run from scratch

### ISSUE THREAD

**Issue by ppieczul** [Kraken-CI/kraken#25]
Prune all volumes, start Kraken 135. Project can be created, but branch creation fails:

Server log:
```
day at 09:55 2020-10-02 07:55:57,518 ERRO p:   11      app:1891  Exception on /api/projects/3/branches [POST]
today at 09:55 Traceback (most recent call last):
today at 09:55 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
today at 09:55 response = self.full_dispatch_request()
today at 09:55 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
today at 09:55 rv = self.handle_user_exception(e)
today at 09:55 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
today at 09:55 reraise(exc_type, exc_value, tb)
today at 09:55 File "/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
today at 09:55 raise value
today at 09:55 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
today at 09:55 rv = self.dispatch_request()
today at 09:55 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
today at 09:55 return self.view_functions[rule.endpoint](**req.view_args)
today at 09:55 File "/venv/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
today at 09:55 response = function(request)
today at 09:55 File "/venv/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
today at 09:55 response = function(request)
today at 09:55 File "/venv/lib/python3.8/site-packages/connexion/decorators/validation.py", line 184, in wrapper
today at 09:55 response = function(request)
today at 09:55 File "/venv/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
today at 09:55 return function(request)
today at 09:55 File "/venv/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
today at 09:55 return function(**kwargs)
today at 09:55 File "/venv/lib/python3.8/site-packages/kraken/server/management.py", line 89, in create_branch
today at 09:55 bs1 = BranchSequences(branch=new_branch, kind=consts.BRANCH_SEQ_FLOW, value=0)
today at 09:55 NameError: name 'BranchSequences' is not defined
```

Postgres log:

```
today at 09:54 The files belonging to this database system will be owned by user "postgres".
today at 09:54 This user must also own the server process.
today at 09:54
today at 09:54 The database cluster will be initialized with locale "en_US.utf8".
today at 09:54 The default database encoding has accordingly been set to "UTF8".
today at 09:54 The default text search configuration will be set to "english".
today at 09:54
today at 09:54 Data page checksums are disabled.
today at 09:54
today at 09:54 fixing permissions on existing directory /var/lib/postgresql/data ... ok
today at 09:54 creating subdirectories ... ok
today at 09:54 selecting default max_connections ... 100
today at 09:54 selecting default shared_buffers ... 128MB
today at 09:54 selecting default timezone ... Etc/UTC
today at 09:54 selecting dynamic shared memory implementation ... posix
today at 09:54 creating configuration files ... ok
today at 09:54 running bootstrap script ... ok
today at 09:54 performing post-bootstrap initialization ... ok
today at 09:54
today at 09:54 WARNING: enabling "trust" authentication for local connections
today at 09:54 You can change this by editing pg_hba.conf or using the option -A, or
today at 09:54 --auth-local and --auth-host, the next time you run initdb.
today at 09:54 syncing data to disk ... ok
today at 09:54
today at 09:54 Success. You can now start the database server using:
today at 09:54
today at 09:54 pg_ctl -D /var/lib/postgresql/data -l logfile start
today at 09:54
today at 09:54 waiting for server to start....2020-10-02 07:54:37.040 UTC [45] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
today at 09:54 2020-10-02 07:54:37.072 UTC [46] LOG:  database system was shut down at 2020-10-02 07:54:36 UTC
today at 09:54 2020-10-02 07:54:37.082 UTC [45] LOG:  database system is ready to accept connections
today at 09:54 done
today at 09:54 server started
today at 09:54 CREATE DATABASE
today at 09:54
today at 09:54
today at 09:54 /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
today at 09:54
today at 09:54 waiting for server to shut down....2020-10-02 07:54:37.552 UTC [45] LOG:  received fast shutdown request
today at 09:54 2020-10-02 07:54:37.553 UTC [45] LOG:  aborting any active transactions
today at 09:54 2020-10-02 07:54:37.557 UTC [45] LOG:  background worker "logical replication launcher" (PID 52) exited with exit code 1
today at 09:54 2020-10-02 07:54:37.557 UTC [47] LOG:  shutting down
today at 09:54 2020-10-02 07:54:37.591 UTC [45] LOG:  database system is shut down
today at 09:54 done
today at 09:54 server stopped
today at 09:54
today at 09:54 PostgreSQL init process complete; ready for start up.
today at 09:54
today at 09:54 2020-10-02 07:54:37.674 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
today at 09:54 2020-10-02 07:54:37.688 UTC [1] LOG:  listening on IPv6 address "::", port 5432
today at 09:54 2020-10-02 07:54:37.695 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
today at 09:54 2020-10-02 07:54:37.738 UTC [63] LOG:  database system was shut down at 2020-10-02 07:54:37 UTC
today at 09:54 2020-10-02 07:54:37.747 UTC [1] LOG:  database system is ready to accept connections
today at 09:54 2020-10-02 07:54:38.313 UTC [70] ERROR:  relation "alembic_version" does not exist at character 73
today at 09:54 2020-10-02 07:54:38.313 UTC [70] STATEMENT:  SELECT alembic_version.version_num AS alembic_version_version_num
today at 09:54 FROM alembic_version
today at 09:54 2020-10-02 07:54:40.906 UTC [72] LOG:  incomplete startup packet
today at 09:54 2020-10-02 07:54:40.998 UTC [73] LOG:  incomplete startup packet
today at 09:54 2020-10-02 07:54:41.399 UTC [74] LOG:  incomplete startup packet
today at 09:54 2020-10-02 07:54:41.434 UTC [75] LOG:  incomplete startup packet
today at 09:54 2020-10-02 07:54:41.444 UTC [76] LOG:  incomplete startup packet
today at 09:55 2020-10-02 07:55:10.558 UTC [80] LOG:  incomplete startup packet
today at 09:55 2020-10-02 07:55:10.638 UTC [81] LOG:  incomplete startup packet
```

**Comment by ppieczul** [comment]
Databases:

```
kraken=# \d
                   List of relations
 Schema |           Name           |   Type   | Owner
--------+--------------------------+----------+--------
 public | agent_assignments        | table    | kraken
 public | agents                   | table    | kraken
 public | agents_groups            | table    | kraken
 public | agents_groups_id_seq     | sequence | kraken
 public | agents_id_seq            | sequence | kraken
 public | alembic_version          | table    | kraken
 public | apscheduler_jobs         | table    | kraken
 public | artifacts                | table    | kraken
 public | artifacts_id_seq         | sequence | kraken
 public | branch_sequences         | table    | kraken
 public | branch_sequences_id_seq  | sequence | kraken
 public | branches                 | table    | kraken
 public | branches_id_seq          | sequence | kraken
 public | files                    | table    | kraken
 public | files_id_seq             | sequence | kraken
 public | flows                    | table    | kraken
 public | flows_id_seq             | sequence | kraken
 public | issues                   | table    | kraken
 public | issues_id_seq            | sequence | kraken
 public | jobs                     | table    | kraken
 public | jobs_id_seq              | sequence | kraken
 public | projects                 | table    | kraken
 public | projects_id_seq          | sequence | kraken
 public | runs                     | table    | kraken
 public | runs_id_seq              | sequence | kraken
 public | secrets                  | table    | kraken
 public | secrets_id_seq           | sequence | kraken
 public | settings                 | table    | kraken
 public | settings_id_seq          | sequence | kraken
 public | stages                   | table    | kraken
 public | stages_id_seq            | sequence | kraken
 public | steps                    | table    | kraken
 public | steps_id_seq             | sequence | kraken
 public | test_case_results        | table    | kraken
 public | test_case_results_id_seq | sequence | kraken
 public | test_cases               | table    | kraken
 public | test_cases_id_seq        | sequence | kraken
 public | tools                    | table    | kraken
 public | tools_id_seq             | sequence | kraken
(39 rows)

```

**Comment by godfryd** [comment]
This was typo in code. It shouldn't be BranchSequences but BranchSequence. Already fixed.
