### ISSUE TITLE
sending emails doesnt work in demo

### ISSUE THREAD

**Issue by godfryd** [Kraken-CI/kraken#58]

**Comment by godfryd** [comment]
exception in celery job:
```
[2020-12-09 19:00:34,908: ERROR/ForkPoolWorker-2] IGNORED EXCEPTION
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/kraken/server/notify.py", line 181, in notify
    _notify_email(run, email)
  File "/venv/lib/python3.8/site-packages/kraken/server/notify.py", line 159, in _notify_email
    server.sendmail(smtp_from, recipients, message.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```

**Comment by godfryd** [comment]
fixed some time ago
