### ISSUE TITLE
Failed to run kraken with default env settings on macOS

### ISSUE THREAD

**Issue by kaka2991** [Kraken-CI/kraken#97]
When starting kraken with default .env it fails on macOS:

Creating kraken-test_server_1           ... error
```

ERROR: for kraken-test_server_1  Cannot start service server: driver failed programming external connectivity on endpoint kraken-test_server_1 (306f85414f4be70da63f9f146db231397129c100bd6f05a294a160b2e476
40fc): Bind for 0.0.0.0:6000 failed: port is already allocated

ERROR: for server  Cannot start service server: driver failed programming external connectivity on endpoint kraken-test_server_1 (306f85414f4be70da63f9f146db231397129c100bd6f05a294a160b2e47640fc): Bind fo
r 0.0.0.0:6000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

It seems that port 6000 is by default used by docker desktop app. I suggest changing 6000 port in example .env (e.g. to 6001) to provide better first impression.

**Comment by ppieczul** [comment]
I have Catalina 10.15.7 with Docker Desktop 3.1.0 and port 6000 is free. I can run Kraken on my MacOS with default .env
Maybe your Docker Desktop was running previous versions of the Kraken containers automatically upon start?

**Comment by ppieczul** [comment]
Actually it does not build today with version v0.406, giving this error:

```
 ---> 1e8b4e1d688a
Step 17/30 : COPY kkagent /server
ERROR: Service 'celery' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat kkagent: file does not exist
```

**Comment by godfryd** [comment]
@ppieczul do you run from the source code repository? Did you update it to the latest? I cannot reproduce it. Could you provide more details?

**Comment by ppieczul** [comment]
I cloned repo, copied dot.env to .env, checked out v0.406 tag and ran docker-composer -f docker-composer.yaml up
Does it make a difference comparing to when I copy the .yaml and .env manually?

**Comment by kaka2991** [comment]
> I have Catalina 10.15.7 with Docker Desktop 3.1.0 and port 6000 is free. I can run Kraken on my MacOS with default .env
> Maybe your Docker Desktop was running previous versions of the Kraken containers automatically upon start?
Nice catch Paweł, you are right. Another instance (from few months ago) was up.

So I think the issue can be closed now.

**Comment by godfryd** [comment]
@ppieczul I cannot reproduce your problem. Next time if you run from the source code repository then just invoke `rake docker_up`. It should run everything correctly.

**Comment by ppieczul** [comment]
Ok, I did not think much and tried the yaml file from the source, not from the release. Building on MacOS does not work because there are binary tools embedded for Linux only. When I take the release yaml and .env everything starts up.

But there is another error when running for the first time on clean docker:
```
File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

return _run_code(code, main_globals, None,

File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

exec(code, run_globals)

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 73, in <module>

main()

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 65, in main

initdb.prepare_initial_data()

File "/venv/lib/python3.8/site-packages/kraken/server/initdb.py", line 127, in prepare_initial_data

stage = Stage.query.filter_by(name="Tests", branch=branch).one_or_none()

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none

ret = list(self)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

util.raise_(

File "/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

raise exception

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^


[SQL: SELECT stages.created AS stages_created, stages.updated AS stages_updated, stages.deleted AS stages_deleted, stages.id AS stages_id, stages.name AS stages_name, stages.description AS stages_description, stages.branch_id AS stages_branch_id, stages.enabled AS stages_enabled, stages.schema AS stages_schema, stages.schema_code AS stages_schema_code, stages.schema_from_repo_enabled AS stages_schema_from_repo_enabled, stages.repo_url AS stages_repo_url, stages.repo_branch AS stages_repo_branch, stages.repo_access_token AS stages_repo_access_token, stages.repo_state AS stages_repo_state, stages.repo_error AS stages_repo_error, stages.repo_version AS stages_repo_version, stages.repo_refresh_interval AS stages_repo_refresh_interval, stages.repo_refresh_job_id AS stages_repo_refresh_job_id, stages.schema_file AS stages_schema_file, stages.triggers AS stages_triggers, stages.timeouts AS stages_timeouts

FROM stages

WHERE stages.name = %(name_1)s AND %(param_1)s = stages.branch_id]

[parameters: {'name_1': 'Tests', 'param_1': 1}]

(Background on this error at: http://sqlalche.me/e/13/f405)

Kraken DB Migration

INFO [alembic.runtime.migration] Context impl PostgresqlImpl.

INFO [alembic.runtime.migration] Will assume transactional DDL.

alembic migration completed

Preparing initial DB data

Traceback (most recent call last):

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

return _run_code(code, main_globals, None,

File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

exec(code, run_globals)

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 73, in <module>

main()

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 65, in main

initdb.prepare_initial_data()

File "/venv/lib/python3.8/site-packages/kraken/server/initdb.py", line 127, in prepare_initial_data

stage = Stage.query.filter_by(name="Tests", branch=branch).one_or_none()

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none

ret = list(self)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

util.raise_(

File "/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

raise exception

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^


[SQL: SELECT stages.created AS stages_created, stages.updated AS stages_updated, stages.deleted AS stages_deleted, stages.id AS stages_id, stages.name AS stages_name, stages.description AS stages_description, stages.branch_id AS stages_branch_id, stages.enabled AS stages_enabled, stages.schema AS stages_schema, stages.schema_code AS stages_schema_code, stages.schema_from_repo_enabled AS stages_schema_from_repo_enabled, stages.repo_url AS stages_repo_url, stages.repo_branch AS stages_repo_branch, stages.repo_access_token AS stages_repo_access_token, stages.repo_state AS stages_repo_state, stages.repo_error AS stages_repo_error, stages.repo_version AS stages_repo_version, stages.repo_refresh_interval AS stages_repo_refresh_interval, stages.repo_refresh_job_id AS stages_repo_refresh_job_id, stages.schema_file AS stages_schema_file, stages.triggers AS stages_triggers, stages.timeouts AS stages_timeouts

FROM stages

WHERE stages.name = %(name_1)s AND %(param_1)s = stages.branch_id]

[parameters: {'name_1': 'Tests', 'param_1': 1}]

(Background on this error at: http://sqlalche.me/e/13/f405)

Kraken DB Migration

INFO [alembic.runtime.migration] Context impl PostgresqlImpl.

INFO [alembic.runtime.migration] Will assume transactional DDL.

alembic migration completed

Preparing initial DB data

Traceback (most recent call last):

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

return _run_code(code, main_globals, None,

File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

exec(code, run_globals)

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 73, in <module>

main()

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 65, in main

initdb.prepare_initial_data()

File "/venv/lib/python3.8/site-packages/kraken/server/initdb.py", line 127, in prepare_initial_data

stage = Stage.query.filter_by(name="Tests", branch=branch).one_or_none()

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none

ret = list(self)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

util.raise_(

File "/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

raise exception

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^


[SQL: SELECT stages.created AS stages_created, stages.updated AS stages_updated, stages.deleted AS stages_deleted, stages.id AS stages_id, stages.name AS stages_name, stages.description AS stages_description, stages.branch_id AS stages_branch_id, stages.enabled AS stages_enabled, stages.schema AS stages_schema, stages.schema_code AS stages_schema_code, stages.schema_from_repo_enabled AS stages_schema_from_repo_enabled, stages.repo_url AS stages_repo_url, stages.repo_branch AS stages_repo_branch, stages.repo_access_token AS stages_repo_access_token, stages.repo_state AS stages_repo_state, stages.repo_error AS stages_repo_error, stages.repo_version AS stages_repo_version, stages.repo_refresh_interval AS stages_repo_refresh_interval, stages.repo_refresh_job_id AS stages_repo_refresh_job_id, stages.schema_file AS stages_schema_file, stages.triggers AS stages_triggers, stages.timeouts AS stages_timeouts

FROM stages

WHERE stages.name = %(name_1)s AND %(param_1)s = stages.branch_id]

[parameters: {'name_1': 'Tests', 'param_1': 1}]

(Background on this error at: http://sqlalche.me/e/13/f405)

Kraken DB Migration

INFO [alembic.runtime.migration] Context impl PostgresqlImpl.

INFO [alembic.runtime.migration] Will assume transactional DDL.

alembic migration completed

Preparing initial DB data

Traceback (most recent call last):

File "/venv

/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

return _run_code(code, main_globals, None,

File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

exec(code, run_globals)

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 73, in <module>

main()

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 65, in main

initdb.prepare_initial_data()

File "/venv/lib/python3.8/site-packages/kraken/server/initdb.py", line 127, in prepare_initial_data

stage = Stage.query.filter_by(name="Tests", branch=branch).one_or_none()

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none

ret = list(self)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

util.raise_(

File "/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

raise exception

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^


[SQL: SELECT stages.created AS stages_created, stages.updated AS stages_updated, stages.deleted AS stages_deleted, stages.id AS stages_id, stages.name AS stages_name, stages.description AS stages_description, stages.branch_id AS stages_branch_id, stages.enabled AS stages_enabled, stages.schema AS stages_schema, stages.schema_code AS stages_schema_code, stages.schema_from_repo_enabled AS stages_schema_from_repo_enabled, stages.repo_url AS stages_repo_url, stages.repo_branch AS stages_repo_branch, stages.repo_access_token AS stages_repo_access_token, stages.repo_state AS stages_repo_state, stages.repo_error AS stages_repo_error, stages.repo_version AS stages_repo_version, stages.repo_refresh_interval AS stages_repo_refresh_interval, stages.repo_refresh_job_id AS stages_repo_refresh_job_id, stages.schema_file AS stages_schema_file, stages.triggers AS stages_triggers, stages.timeouts AS stages_timeouts

FROM stages

WHERE stages.name = %(name_1)s AND %(param_1)s = stages.branch_id]

[parameters: {'name_1': 'Tests', 'param_1': 1}]

(Background on this error at: http://sqlalche.me/e/13/f405)

Kraken DB Migration

INFO [alembic.runtime.migration] Context impl PostgresqlImpl.

INFO [alembic.runtime.migration] Will assume transactional DDL.

alembic migration completed

Preparing initial DB data

Traceback (most recent call last):

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column stages.repo_state does not exist

LINE 1: ...es.repo_access_token AS stages_repo_access_token, stages.rep...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

return _run_code(code, main_globals, None,

File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

exec(code, run_globals)

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 73, in <module>

main()

File "/venv/lib/python3.8/site-packages/kraken/migrations/apply.py", line 65, in main

initdb.prepare_initial_data()

File "/venv/lib/python3.8/site-packages/kraken/server/initdb.py", line 127, in prepare_initial_data

stage = Stage.query.filter_by(name="Tests", branch=branch).one_or_none()

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none

ret = list(self)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/venv/lib/python3.8/site-
```

**Comment by godfryd** [comment]
@ppieczul in these logs it seems that there is some database content, so it is not a clean environment. Try first cleaning it totally with: 

```console
docker-compose ..... down -v
```
-v deletes volumens where database data files are stored.

**Comment by godfryd** [comment]
@ppieczul after cleaning, try to start again with 0.413 version this way:

```console
docker-compose --env-file kraken-0.413.env -f kraken-docker-compose-0.413.yaml up
```

**Comment by ppieczul** [comment]
Ok, it works fine now. Thanks
